export const Language = {
  AUTO_DETECT: 'Auto-detect Language',
  ARABIC: 'Arabic',
  BIKOL: 'Bikol',
  CEBUANO: 'Cebuano',
  ENGLISH: 'English',
  FRENCH: 'French',
  GERMAN: 'German',
  HINDI: 'Hindi',
  ILOCANO: 'Ilocano',
  ILONGGO: 'Ilonggo (Hiligaynon)',
  INDONESIAN: 'Indonesian',
  ITALIAN: 'Italian',
  JAPANESE: 'Japanese',
  KOREAN: 'Korean',
  MANDARIN: 'Mandarin Chinese',
  PORTUGUESE: 'Portuguese',
  RUSSIAN: 'Russian',
  SPANISH: 'Spanish',
  TAGALOG: 'Tagalog',
  THAI: 'Thai',
  VIETNAMESE: 'Vietnamese',
  WARAY: 'Waray',
};
